import { getCookiesForUrl } from "../lib/cookies.ts";
import type { PendingDownload } from "../lib/types.ts";
import { openDownloadPopup } from "./popupWindow.ts";
import {
  consumeBypassFlag,
  isAllowedDownload,
  isAllowedDownloadId,
  setPendingDownload,
} from "./state.ts";

function extractFilename(path: string | undefined): string | null {
  if (!path) return null;
  return path.split("/").pop()!.split("\\").pop() ?? null;
}

const interceptedDownloadIds = new Set<number>();

chrome.downloads.onDeterminingFilename.addListener((item, suggest) => {
  console.log("[ADM] onDeterminingFilename:", item.url, "finalUrl:", item.finalUrl, "filename:", item.filename, "state:", item.state);

  // Skip data URLs (e.g. command text files generated by the extension itself)
  if (item.url.startsWith("data:") || (item.finalUrl && item.finalUrl.startsWith("data:"))) {
    suggest();
    return;
  }

  if (consumeBypassFlag()) {
    console.log("[ADM] skipped: bypass flag was set");
    suggest();
    return;
  }
  if (
    isAllowedDownloadId(item.id) ||
    isAllowedDownload(item.url) ||
    (item.finalUrl && isAllowedDownload(item.finalUrl))
  ) {
    console.log("[ADM] skipped: url or id was pre-allowed");
    suggest();
    return;
  }

  // Prevent duplicate cancel/handling if onDeterminingFilename fires multiple times
  if (interceptedDownloadIds.has(item.id)) {
    console.log("[ADM] skipped: download already intercepted:", item.id);
    return;
  }
  interceptedDownloadIds.add(item.id);
  if (interceptedDownloadIds.size > 500) {
    const oldest = interceptedDownloadIds.values().next().value;
    if (oldest !== undefined) interceptedDownloadIds.delete(oldest);
  }

  // 1. Call suggest() synchronously to complete the onDeterminingFilename phase.
  // Chrome requires onDeterminingFilename listeners to call suggest() before the download
  // can transition to 'in_progress'. Calling cancel() before suggest() triggers
  // "Unchecked runtime.lastError: Download must be in progress".
  suggest();

  // 2. Cancel the download now that it is in_progress.
  // Use an explicit callback checking chrome.runtime.lastError so Chrome's C++ bindings
  // mark the error as checked and never emit an unchecked runtime.lastError warning.
  chrome.downloads.cancel(item.id, () => {
    const err = chrome.runtime.lastError;
    if (err) {
      console.debug("[ADM] Cancel notice:", err.message);
    } else {
      chrome.downloads.erase({ id: item.id }, () => {
        void chrome.runtime.lastError;
      });
    }
  });

  // item.finalUrl is Chrome's post-redirect URL resolved after all HTTP redirects
  // and authentication handshakes have completed.
  const finalUrl = item.finalUrl || item.url;
  const originalFilename = extractFilename(item.filename);

  (async () => {
    const pending: PendingDownload = {
      url: finalUrl,
      originalUrl: item.url,
      filename: originalFilename,
      referrer: item.referrer || null,
      mime: item.mime || null,
      fileSize: item.fileSize ?? null,
      cookies: await getCookiesForUrl(finalUrl, [item.url, item.referrer]),
      timestamp: Date.now(),
    };

    setPendingDownload(pending);
    await openDownloadPopup();
  })().catch((error) => {
    console.error("[ADM] Failed to process intercepted download:", error);
  });
});
