import { getCookiesForUrl } from "../lib/cookies.ts";
import type { PendingDownload } from "../lib/types.ts";
import { openDownloadPopup } from "./popupWindow.ts";
import { consumeAllowedDownload, consumeBypassFlag, setPendingDownload } from "./state.ts";

function extractFilename(path: string | undefined): string | null {
  if (!path) return null;
  return path.split("/").pop()!.split("\\").pop() ?? null;
}

chrome.downloads.onDeterminingFilename.addListener((item, suggest) => {
  console.log("[ADM] onDeterminingFilename:", item.url, "finalUrl:", item.finalUrl, "filename:", item.filename);

  // Skip data URLs (e.g. command text files generated by the extension itself)
  if (item.url.startsWith("data:") || (item.finalUrl && item.finalUrl.startsWith("data:"))) {
    suggest();
    return;
  }

  if (consumeBypassFlag()) {
    console.log("[ADM] skipped: bypass flag was set");
    suggest();
    return;
  }
  if (consumeAllowedDownload(item.url) || (item.finalUrl && consumeAllowedDownload(item.finalUrl))) {
    console.log("[ADM] skipped: url was pre-allowed");
    suggest();
    return;
  }

  try {
    chrome.downloads.cancel(item.id, () => {
      chrome.downloads.erase({ id: item.id }).catch(() => {});
    });
  } catch (error) {
    console.error("[ADM] Failed to intercept download:", error);
  }

  suggest();

  // item.finalUrl is Chrome's post-redirect URL resolved after all HTTP redirects
  // and authentication handshakes have completed.
  const finalUrl = item.finalUrl || item.url;
  const originalFilename = extractFilename(item.filename);

  (async () => {
    const pending: PendingDownload = {
      url: finalUrl,
      originalUrl: item.url,
      filename: originalFilename,
      referrer: item.referrer || null,
      mime: item.mime || null,
      fileSize: item.fileSize ?? null,
      cookies: await getCookiesForUrl(finalUrl, [item.url, item.referrer]),
      timestamp: Date.now(),
    };

    setPendingDownload(pending);
    await openDownloadPopup();
  })().catch((error) => {
    console.error("[ADM] Failed to process intercepted download:", error);
  });
});
