import { getCookiesForUrl } from "../lib/cookies.ts";
import type { PendingDownload } from "../lib/types.ts";
import { openDownloadPopup } from "./popupWindow.ts";
import {
  consumeAllowedDownload,
  consumeAllowedDownloadId,
  consumeBypassFlag,
  setPendingDownload,
} from "./state.ts";

function extractFilename(path: string | undefined): string | null {
  if (!path) return null;
  return path.split("/").pop()!.split("\\").pop() ?? null;
}

chrome.downloads.onDeterminingFilename.addListener((item, suggest) => {
  console.log("[ADM] onDeterminingFilename:", item.url, "finalUrl:", item.finalUrl, "filename:", item.filename);

  // Skip data URLs (e.g. command text files generated by the extension itself)
  if (item.url.startsWith("data:") || (item.finalUrl && item.finalUrl.startsWith("data:"))) {
    suggest();
    return;
  }

  if (consumeBypassFlag()) {
    console.log("[ADM] skipped: bypass flag was set");
    suggest();
    return;
  }
  if (
    consumeAllowedDownloadId(item.id) ||
    consumeAllowedDownload(item.url) ||
    (item.finalUrl && consumeAllowedDownload(item.finalUrl))
  ) {
    console.log("[ADM] skipped: url or id was pre-allowed");
    suggest();
    return;
  }

  try {
    chrome.downloads.cancel(item.id, () => {
      // Accessing chrome.runtime.lastError clears "Unchecked runtime.lastError"
      const cancelErr = chrome.runtime.lastError;
      if (cancelErr) {
        console.debug("[ADM] downloads.cancel notice:", cancelErr.message);
      }
      chrome.downloads.erase({ id: item.id }, () => {
        const eraseErr = chrome.runtime.lastError;
        if (eraseErr) {
          console.debug("[ADM] downloads.erase notice:", eraseErr.message);
        }
      });
    });
  } catch (error) {
    console.error("[ADM] Failed to intercept download:", error);
  }

  // NOTE: Do NOT call suggest() here!
  // According to Chrome's onDeterminingFilename API docs:
  // "If the download is canceled, suggest does not need to be called."
  // Calling suggest() allows Chrome to continue downloading in parallel with cancel(),
  // which causes fast downloads to complete before cancel() runs, triggering
  // "Unchecked runtime.lastError: Download must be in progress".

  // item.finalUrl is Chrome's post-redirect URL resolved after all HTTP redirects
  // and authentication handshakes have completed.
  const finalUrl = item.finalUrl || item.url;
  const originalFilename = extractFilename(item.filename);

  (async () => {
    const pending: PendingDownload = {
      url: finalUrl,
      originalUrl: item.url,
      filename: originalFilename,
      referrer: item.referrer || null,
      mime: item.mime || null,
      fileSize: item.fileSize ?? null,
      cookies: await getCookiesForUrl(finalUrl, [item.url, item.referrer]),
      timestamp: Date.now(),
    };

    setPendingDownload(pending);
    await openDownloadPopup();
  })().catch((error) => {
    console.error("[ADM] Failed to process intercepted download:", error);
  });
});
